### ISSUE TITLE
Tcm security 

### ISSUE THREAD

**Issue by Th3Samaritan** [rajprasad12/Cyber-Security-Resources#7]
Pls add practical web application hacking and security by Adams Heath please and thanks for all you do ✌🏾

**Comment by mttaggart** [comment]
Hello,

As the author and copyright holder of "Practical Web Application Security and Testing," I will inform you that distribution and viewing of my course is authorized only through purchase on TCM Academy. Should I see my course appear here, I will submit a DMCA takedown request in addition to the ones already submitted for the current TCM content on this repository.

**Comment by Th3Samaritan** [comment]
Ooh wow, I literally thought the owner of this repo was approved by you guys absolutely sorry if you find this offensive

**Comment by dievus** [comment]
Why in the world would we make our paid courses freely available here and through Mega.nz?

**Comment by Th3Samaritan** [comment]
Honestly look I was jst invited to this page randomly am not the owner of the page I took my courses directly from Tcm academy bcos I want the certificate, I was jst told to pls check it out if there is any thing he’s supposed to tell the owners to add
